#!/usr/bin/env bash
set -euo pipefail

echo "Testing lrh ..."

if [ "$#" -eq 0 ]; then
    set -x
    python -m unittest discover -s tests -p "*_test.py"
elif [ -d "$1" ]; then
    set -x
    python -m unittest discover -s "$1" -p "*_test.py"
elif [ -f "$1" ]; then
    module="${1%.py}"
    module="${module#./}"
    module="${module//\//.}"
    set -x
    python -m unittest "$module"
else
    set -x
    python -m unittest "$@"
fi

{ set +x; } 2>/dev/null
echo